services:
  # Backend Service (Node.js API)
  backend:
    image: prajwal213/contact-manager-backend:latest # Changed from 'build'
    container_name: backend_api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}

  # Frontend Service (React App)
  frontend:
    image: prajwal213/contact-manager-frontend:latest # Changed from 'build'
    container_name: frontend_client
    ports:
      - "3000:80"
    depends_on:
      - backend

networks:
  default:
    driver: bridge