version: '3.8'

services:
  # Backend Service (Node.js API)
  backend:
    build: ./backend
    container_name: backend_api
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    environment:
      - MONGO_URI=${MONGO_URI}

  # Frontend Service (React App)
  frontend:
    build: ./frontend
    container_name: frontend_client
    ports:
      - "3000:80"
    depends_on:
      - backend

networks:
  default:
    driver: bridge
    